spring:
  datasource:
    username: root
    password: 18772305906
    url: jdbc:mysql://localhost:3306/bill?serverTimezone=GMT%2B8

    #8.x版本驱动包，要使用以下类作为驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver

    #指定Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource


    # 数据源其他配置, DataSourceProperties中没有相关属性,默认无法绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,logback
    maxPoolPreparedStatementPerConnectionSize: 25
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


# mybatis相关配置文件

mybatis:

  # mybatis核心配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml

  # mybatis映射配置文件位置

  mapper-locations: classpath:mybatis/mapper/*.xml

#打印sql
logging:
  level:
    com.lcw.msgspringboot08datamybatis.mapper: debug