spring:
  datasource:
    username: root
    password: 18772305906
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    # 8.x版本驱动包，要使用以下类作为驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver

#    type: com.alibaba.druid.pool.DruidDataSource



  # jpa相关配置 spring.jpa.*
  jpa:
    showSql: true  #控制台显示sql

    #  会根据就映射实体类自动创建或更新数据表
    hibernate:
      ddl-auto: update


     #  默认创建表类型是MyISAM，是非事务安全的，所以无法实现事物回滚
     # 指定如下方言: 创建的表类型是Innodb，才可以进行对事物的回滚。
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQLDialect






