server:
  port: 10087
spring:
  application:
    name: api-gateway
zuul:
  routes:
    user-service: #这里是路由id，随意写
      path: /user-service/**  #这里是映射路径
      url: http://127.0.0.1:9098  #映射路径对应的实际url路径
  prefix: /api #添加路由前缀
##      serviceId: user-service #服务id
#     /user-service/**

eureka:
  client:
    registry-fetch-interval-seconds: 5 #获取服务列表的周期5s
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
